name: Gradle Dependency Submission

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set execute permissions for gradlew
        run: chmod +x gradlew
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}