name: Release Deployment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@2
        with:
          arguments: shadowJar
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Rename the JAR
        run: mv build/libs/WineStock-${{ steps.get_version.outputs.VERSION }}-shadow.jar build/libs/WineStock-${{ matrix.os }}.jar
      - name: Upload the JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/WineStock-${{ matrix.os }}.jar
          asset_name: WineStock-${{ matrix.os }}.jar
          asset_content_type: application/java-archive